apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: sphinx-coininfo-ingress
  namespace: kube-system
  annotations:
    k8s.kuboard.cn/displayName: sphinx-coininfo
    k8s.kuboard.cn/workload: sphinx-coininfo
    kubernetes.io/ingress.class: "traefik-internet"
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: kube-system-strip-sphinx-coininfo-prefix@kubernetescrd,kube-system-common-headers@kubernetescrd

spec:
  rules:
    - host: api.npool.top
      http: &http_rules
        paths:
          - path: /api/sphinx-coininfo
            backend:
              serviceName: sphinx-coininfo
              servicePort: 50150
    - host: api.xpool.top
      http: *http_rules
    - host: www.npool.top
      http: *http_rules
    - host: www.xpool.top
      http: *http_rules

---

apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-sphinx-coininfo-prefix
  namespace: kube-system
spec:
  stripPrefix:
    prefixes:
      - /api/sphinx-coininfo
